import os
import pandas as pd
from dotenv import load_dotenv
from groq import Groq

# Load environment variables from the .env file
# Access the Groq API key (should be securely stored in the .env file (not provided, must be generated by user))
# Instantiate the Groq client with API key
load_dotenv()
api_key = os.getenv("GROQ_API_KEY")
client = Groq(api_key=api_key)

# This prompt structure is adapted from the prompt example B.5. from the research paper: "Curated LLM: Synergy of LLMs and Data Curation for tabular augmentation in low-data regimes" (Seedatk, Huynh, et al.) https://arxiv.org/pdf/2312.12112 
# The template is currently adapted to the 'insurance.csv' dataset (referenced in README.md)
prompt_template_baseline = """
System Role: You are a professional poker coach who provides detailed, structured explanations for poker decision-making.
You have access to the game state summary and the recommended preflop decision below.

Game State Summary:
{game_summary}

Recommended Preflop Decision:
{recommended_decision}

Please provide a clear, structured explanation in numbered bullet points as to why the recommended decision is optimal.
Reference factors such as your hole card strength, table position, pot size relative to blinds, and any other relevant elements.
"""

# Function to generate synthetic data using a model and prompt
def generate_response(model_name, game_summary, recommended_decision):

    prompt = prompt_template_baseline.format(game_summary=game_summary, recommended_decision=recommended_decision)
    
    try:
        # Create a chat completion using the Groq API
        response = client.chat.completions.create(
            messages=[
                {
                    "role": "user", 
                    "content": prompt
                }
            ],
            model=model_name,
            #response_format={"type": "json_object"} Turn on for JSON beta mode
            temperature=1.0
        )
        
        # Print the full response for debugging
        print("Full Response:", response)
        
        generated_response = response.choices[0].message.content if response.choices else "No output"
        
        return generated_response
    except Exception as e:
        print(f"Error generating data with model {model_name}: {e}")
        return None
